### ISSUE TITLE
Issue with OpenJ9

### ISSUE THREAD

**Issue by Artuto** [dmulloy2/ProtocolLib#622]
_Follow this template except for feature requests. Use pastebin when providing /protocol dump and any relevant errors._

Make sure you've done the following:
- [x] You're using the latest build for your server version
- [x] This isn't an issue caused by another plugin
- [x] You've checked for duplicate issues
- [x] You didn't use `/reload`

Debug paste link: https://gist.github.com/Artuto/00e0e638a19509322f25c440947db833#file-dump-log

Description and relevant errors:

Getting these errors since I switched to OpenJDK 8 OpenJ9: https://gist.github.com/Artuto/00e0e638a19509322f25c440947db833#file-error-log

**Comment by maxlehot1234** [comment]
hastebin are empty, just saying :) Always do this to me, so I use other things like: https://gist.github.com

**Comment by Artuto** [comment]
They both work for me but here it is: https://gist.github.com/Artuto/00e0e638a19509322f25c440947db833

**Comment by dmulloy2** [comment]
Java 9 is not currently supported, and it will not be until/unless Spigot updates.

**Comment by MiniDigger** [comment]
Openj9 != Java 9

J9 is IBMs own implementation of Java that they recently ~killed~ donated to eclipse.

Both spigot and protocollib run on newer versions of the official openjdk without any issues for me. I can't say the same for j9.

**Comment by Artuto** [comment]
We are currently using Paper 1.13 and Bungee with OpenJ9 just fine. Its a ProtocolLib specific problem. Also, yeah OpenJ9 != Java 9.

We're using OpenJDK8 with OpenJ9 (worst name scheme)

**Comment by maxlehot1234** [comment]
@dmulloy2 Why you close this?

I have Java 8 on my server.

I also try it on my computer (localhost server) and I have Java 8.

It was a protocollib issue...

Any way to fix this?

**Comment by Artuto** [comment]
@dmulloy2 Can it be reopened? Its a shame ProtocolLib wont work in OpenJ9

**Comment by dmulloy2** [comment]
I was confused by the name and had assumed it was Java 9.

Anyway, the actual solution for this is to grab a dev build because this issue was fixed a while back.

**Comment by Artuto** [comment]
Do you have a link? Happy to test it.

**Comment by dmulloy2** [comment]
@Artuto http://ci.dmulloy2.net/job/ProtocolLib%20Gradle/

**Comment by Artuto** [comment]
Can confirm its fixed. Closing.

**Comment by galacticwarrior9** [comment]
Can confirmed not fixed for the latest [1.13.2 dev build](http://ci.dmulloy2.net/job/ProtocolLib/425/). Is it possible to backport the fix?
