### ISSUE TITLE
Issue with ProtocolLib and Holographic Displays

### ISSUE THREAD

**Issue by MuffinChris** [dmulloy2/ProtocolLib#629]
`13.06 13:31:16 [Server] ERROR [HolographicDisplays] Unhandled exception occured in onPacketSending(PacketEvent) for HolographicDisplays
13.06 13:31:16 [Server] INFO java.lang.RuntimeException: Cannot retrieve entity from ID.
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:648) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:627) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.readInternal(StructureModifier.java:227) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.reflect.StructureModifier.read(StructureModifier.java:195) ~[?:?]
13.06 13:31:16 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:70) ~[?:?]
13.06 13:31:16 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.packet.WrapperPlayServerSpawnEntityLiving.getEntity(WrapperPlayServerSpawnEntityLiving.java:79) ~[?:?]
13.06 13:31:16 [Server] INFO at com.gmail.filoghost.holographicdisplays.bridge.protocollib.current.ProtocolLibHookImpl$1.onPacketSending(ProtocolLibHookImpl.java:134) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:364) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:63) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:329) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:299) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.b(NetworkManager.java:208) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.NetworkManager.sendPacket(NetworkManager.java:171) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1553) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerConnection.sendPacket(PlayerConnection.java:1526) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.EntityTrackerEntry.a(EntityTrackerEntry.java:276) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.EntityTrackerEntry.b(EntityTrackerEntry.java:260) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.updatePlayer(PlayerChunkMap.java:1249) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap$EntityTracker.track(PlayerChunkMap.java:1264) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:993) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:483) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1144) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:372) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-81]
13.06 13:31:16 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]
13.06 13:31:16 [Server] INFO Caused by: com.comphenix.protocol.reflect.FieldAccessException: Cannot find entity from ID 102.
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:222) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
13.06 13:31:16 [Server] INFO ... 35 more
13.06 13:31:16 [Server] INFO Caused by: java.lang.IllegalArgumentException: Cannot get Bukkit entity from EntityNMSArmorStand[''/102, uuid='7d4f12e8-2207-478d-a355-804ab4a07448', l='world', x=63.56, y=92.77, z=11.11, cx=3, cz=0, tl=0, v=false, d=false]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.utility.MinecraftReflection.getBukkitEntity(MinecraftReflection.java:370) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.EntityUtilities.getEntityFromID(EntityUtilities.java:220) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.injector.PacketFilterManager.getEntityFromID(PacketFilterManager.java:932) ~[?:?]
13.06 13:31:16 [Server] INFO at com.comphenix.protocol.wrappers.BukkitConverters$9.getSpecific(BukkitConverters.java:642) ~[?:?]
13.06 13:31:16 [Server] INFO ... 35 more
13.06 13:31:16 [Server] INFO Caused by: java.lang.RuntimeException: An internal error occured.`

This happens whenever a Player logs in.
I am using Holographic Displays to display damage indicators, and using ProtocolLib to disable the Damage Indicator particle via packets.

Whenever I log in, the server crashes.

**Comment by dmulloy2** [comment]
Should be fixed in the new dev builds, which build are you using?

**Comment by MuffinChris** [comment]
I should be on the latest from May 7th or whatever, let me check again.

**Comment by MuffinChris** [comment]
I'm on 4.5.0-Snapshot, should be latest.

**Comment by MuffinChris** [comment]
I deleted and re-created a new world, issue is still happening.
Holographic Displays 2.3.3 and 4.5.0-Snapshot ProtocolLib

**Comment by bundabrg** [comment]
References: https://github.com/filoghost/HolographicDisplays/issues/135

Please refer to the above for some more info. At the moment we think the issue may be in ProtocolLib and due to some structural changes in the 1.14 code and/or the spigot changes on top (it's tricky because there's another error that pops up referencing methods removed by spigot and are not related to this particular error)
