### ISSUE TITLE
Maven repository runs in low disk-space so artifacts cannot be downloaded

### ISSUE THREAD

**Issue by DiscowZombie** [dmulloy2/ProtocolLib#703]
Hello, 

since approximate two hours, my team and I are unable to download artifacts coming from [your Maven repository](http://repo.dmulloy2.net/nexus/repository/public/) (a 500 error is returned). After a little research, we found that this issue is caused by a low-disk space on the machine hosting the database attached with the Maven repository ([as demonstrated on this page](http://repo.dmulloy2.net/nexus/repository/releases/com/comphenix/protocol/ProtocolLib/4.4.0/ProtocolLib-4.4.0.jar)):
```java
javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (6 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 256 MB. Required space is now set to 256MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) . DB name="component" 
```

*Disclaimer: I know that this issue is not directly related to ProtocolLib but developers are affected significantly, and that's the only place I found to warn about it.*

**Comment by Th0rgal** [comment]
> Hello,
> 
> since approximate two hours, my team and I are unable to download artifacts coming from [your Maven repository](http://repo.dmulloy2.net/nexus/repository/public/) (a 500 error is returned). After a little research, we found that this issue is caused by a low-disk space on the machine hosting the database attached with the Maven repository ([as demonstrated on this page](http://repo.dmulloy2.net/nexus/repository/releases/com/comphenix/protocol/ProtocolLib/4.4.0/ProtocolLib-4.4.0.jar)):
> 
> ```java
> javax.servlet.ServletException: com.orientechnologies.orient.core.exception.OLowDiskSpaceException: Error occurred while executing a write operation to database 'component' due to limited free space on the disk (6 MB). The database is now working in read-only mode. Please close the database (or stop OrientDB), make room on your hard drive and then reopen the database. The minimal required space is 256 MB. Required space is now set to 256MB (you can change it by setting parameter storage.diskCache.diskFreeSpaceLimit) . DB name="component" 
> ```
> 
> _Disclaimer: I know that this issue is not directly related to ProtocolLib but developers are affected significantly, and that's the only place I found to warn about it._

I confirm: I'm unable to use ProtocolLib with maven or gradle

**Comment by aroooo** [comment]
Same, was forced to remove the repository and ProtocolLib from my pom.xml!

**Comment by DiscowZombie** [comment]
Update: Sound like the Maven repository is offline now.

**Comment by aroooo** [comment]
@dmulloy2 any update ?

**Comment by bundabrg** [comment]
dmulloy2 let me know if you need a hosted maven repo but I assume it just needs some love.

**Comment by bundabrg** [comment]
Till things are resolved I've mirrored to mine. Use the following repo definition:
```
        <!-- Bundabrg's Repo -->
        <repository>
            <id>bundabrg-repo</id>
            <url>https://repo.worldguard.com.au/repository/maven-public</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
```

**Comment by hornta** [comment]
@bundabrg Thanks. Hjälten vi behöver

**Comment by hornta** [comment]
@bundabrg no doesn't work :-/

**Comment by hornta** [comment]
![image](https://user-images.githubusercontent.com/4553604/66769528-a4082800-eeb5-11e9-93dd-2b3a6c4eb1ac.png)

**Comment by FelixKlauke** [comment]
@bundabrg @hornta Just add a trailing slash to the repo url :) But you will still get errors as his repo might provide ProtocolLib, but no further dependencies like BukkitExecutors.

**Comment by bundabrg** [comment]
I provide that as well and have modified protocollib-parent pom to remove the repos in there.

You may need to remove ~./m2/repositories/com/comphenix then perform a mvn -U clean install

@hornta

**Comment by wmelo92** [comment]
Hi, Can anyone host protocollib 4.5.0 (latest build)?

**Comment by Yun-Shan** [comment]
@wmelo92 @hornta 
i uploaded it to a temporary repo
only 4.4.0, build425, i am sorry but i don't have 4.5.0
i will delete it when official repo online
repo url: https://dl.bintray.com/yun-shan/ProtocolLib-Temporary/
gradle example
```
    maven {
        name 'ProtocolLib Repo'
        // url 'http://repo.dmulloy2.net/nexus/repository/public/'
        url 'https://dl.bintray.com/yun-shan/ProtocolLib-Temporary/'
    }
```

**Comment by sgdc3** [comment]
Hello, I'm hosting both 4.4.0 and 4.5.0 on [repo.codemc.org](https://repo.codemc.org)

You can also check the automatic build jobs for both branches at:
https://ci.codemc.io/job/ThirdParty/job/ProtocolLib/
https://ci.codemc.io/job/ThirdParty/job/ProtocolLib-Legacy/

```
<repository>
    <id>codemc-repo</id>
    <url>https://repo.codemc.org/repository/maven-public/</url>
</repository>
```

**Comment by dmulloy2** [comment]
Should be coming back up now.

Sorry for the delay, was on vacation

**Comment by bundabrg** [comment]
Thanks for keeping this excellent plugin going.

out of interest sake @sgdc3 how do you handle ProtocolLib-Parent pom adding the (then) broken repo back into the mix thus invalidating the ability to host a mirror? I'm thinking of adding 3rd party compiles but get caught by this often.

**Comment by sgdc3** [comment]
@bundabrg 😎 
<img width="755" alt="Cattura" src="https://user-images.githubusercontent.com/8779252/66921512-ae493400-f025-11e9-9811-407617447604.PNG">

**Comment by sgdc3** [comment]
@pixar02 with the official repo? try with the "-B -U clean package" maven scope

**Comment by pixar02** [comment]
Thanks that fixed it.
